name: Create new Release

# Run on a push to master, and everyday at 4:20
on:
  push:
    branches: [ 'master' ]
  schedule:
    - cron: '20 4 * * *'

env:
  LATEST_RASPBIAN: https://downloads.raspberrypi.org/raspbian_lite_latest
  ALL_OWN_RELEASES: https://api.github.com/repos/$GITHUB_REPOSITORY/releases

jobs:
  check:
    name: Check new Raspbian Release
    runs-on: ubuntu-latest

    steps:
      - name: Check for new Release
        id: check
        run: |
          URL="$(curl -ILs -o /dev/null -w %{url_effective} "$LATEST_RASPBIAN")"
          echo ::set-output name=url::"$URL"

          if ! TAGS="$(curl -s "$ALL_OWN_RELEASES" | jq -r '.[].tag_name')"; then
            echo "::set-output name=release::true"
            exit 0
          fi

          VERSION="$(echo "$URL" | grep -oE '\d{4}-\d{2}-\d{2}-raspbian.*.zip' | cut -d- -f-3)"
          echo ::set-output name=VERSION::"$VERSION"

          if ! echo "$TAGS" | grep "^$VERSION"; then
            echo "::set-output name=release::true"
          fi

  release:
    name: Release a release
    runs-on: ubuntu-latest

    if: steps.check.outputs.release == 'true'

    steps:
      - name: aaaa
        run: echo 'aaaa'


