name: Create new Release

# Run on a push to master, and everyday at 4:20
on:
  push:
    branches: [ 'master' ]
  schedule:
    - cron: '20 4 * * *'

env:
  LATEST_RASPBIAN: https://downloads.raspberrypi.org/raspbian_lite_latest
  ALL_OWN_RELEASES: https://api.github.com/repos/$GITHUB_REPOSITORY/releases

jobs:
  check:
    name: Check new Raspbian Release
    runs-on: ubuntu-latest

    steps:
      - name: Get direct URL of latest Raspbian release
        run: echo ::set-env name=URL::"$(curl -ILs -o /dev/null -w %{url_effective} "$LATEST_RASPBIAN")"

      - name: Get date-VERSION of latest Raspbian release
        run: echo ::set-env name=VERSION::"$(echo "$URL" | grep -oE '\d{4}-\d{2}-\d{2}' | tail -n1)"

      - name: Get all own releases
        run: echo ::set-env name=TAGS::"$(wget -qO- "$ALL_OWN_RELEASES" | jq -r '.[].tag_name')"

      - name: Check if latest release is in own releases
        run: echo "$TAGS" | grep "^$VERSION"


      - name: Create release
        if: failure()
        run: echo "Creating release…"
