name: Create new Release

# Run on a push to master, and everyday at 4:20
on:
  push:
    branches: [ 'master' ]
  schedule:
    - cron: '20 4 * * *'

jobs:
  check:
    name: Check new Raspbian Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check
        env:
          ALL_OWN_RELEASES: https://api.github.com/repos/$GITHUB_REPOSITORY/releases
        run: |
          VERSION="$(./modify-image.sh version)"

          TAGS="$(wget -qO- "$ALL_OWN_RELEASES" | jq -r '.[].tag_name')"
          if [ -n "$TAGS" ] && echo "$TAGS" | grep "$VERSION"; then
            echo "Nothing to do. Exiting."
            exit 0
          fi
          echo ::set-env name=VERSION::"$VERSION"


      - name: Build Docker image
        if: env.VERSION != ''
        run: docker build -t builder .

      - name: Modify Raspbian image
        if: env.VERSION != ''
        run: |
          mkdir images/
          docker run --rm --privileged -v="$(pwd)/images/:/raspbian/" builder

          echo ::set-env name=FILE::"$(cd images && ls *-firstboot.zip)"

      - name: Create Github Release
        uses: meeDamian/github-release@2.0
        if: env.VERSION != '' && env.FILE != ''
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.VERSION }}
          name: ${{ env.FILE }}
          draft: true
          prerelease: true
          allow_override: false
          gzip: false
          files: >
            images/${{ env.FILE }}
            images/${{ env.FILE }}.sha256
          body: >
            This Release adds [`firstrun.sh`](/firstrun.sh) capabilities to
            the original Raspbian image [${{ env.FILE }}](${{ env.URL }}).

      - name: Comment
        if: steps.release.outputs.release_id != ''
        env:
          URL: https://api.github.com/repos/$GITHUB_REPOSITORY/issues
          body: >
            Release https://github.com/$GITHUB_REPOSITORY/releases/tag/$VERSION has been created.

            It's based on $FILE bla bla
        run: |
          jq -nc \
            --arg title "Raspbian $VERSION has been released" \
            --arg body "$(echo "$body" | sed ':a;N;$!ba;s/\n/\\n/g')")" \
            --argjson assignees '["meeDamian"]' \
            --argjson labels '["pending-approval"]' \
            '{$title, $body, $assignees, $labels}' \
          | curl -d @- \
            -X "POST" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "$URL"
