name: Create new Release

# Run on a push to master, and everyday at 4:20
on:
  push:
    branches: [ 'master' ]
  schedule:
    - cron: '20 4 * * *'

jobs:
  check:
    name: Check new Raspbian Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check
        env:
          ALL_OWN_RELEASES: https://api.github.com/repos/$GITHUB_REPOSITORY/releases
        run: |
          ls -la /usr/bin/env
          echo '----'
          ./modify-image.sh version
          echo '-----'
          VERSION="$(./modify-image.sh version)"
          echo '-----'

#          TAGS="$(wget -qO- "$ALL_OWN_RELEASES" | jq -r '.[].tag_name')"
#          if [ -n "$TAGS" ] && echo "$TAGS" | grep "$VERSION"; then
#            echo "Nothing to do. Exiting."
#            exit 0
#          fi
#
#          echo ::set-env name=do::"Yaaaaaaas"

      - name: Build
        if: env.DO != ''
        run: mkdir images/ && docker build -t builder .

      - name: Run
        if: env.DO != ''
        run: docker run --rm --privileged -v="$(pwd)/images/:/raspbian/" builder



#      - name: Create Release
#        uses: meeDamian/github-release@2.0
#        if: env.URL != ''
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          tag: ${{ env.VERSION }}
#          name: ${{ env.FILE }}
#          draft: true
#          prerelease: true
#          allow_override: false
#          body: |
#            This Release adds [`firstrun.sh`](/firstrun.sh) capabilities to original Raspbian image [${{ env.FILE }}](${{ env.URL }}).
